"""Regenerate scenes/sources.js from the beast sketches in scenes/*.js.

player.html can't fetch() scene files when opened from file:// (CORS), so the
scene sources are baked into one generated script that registers them on
window.SCENES. Run this after adding or editing any scenes/<beast>.js:

    python tools/build_player_sources.py
"""

import json
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SCENES = Path(__file__).resolve().parent.parent / "scenes"


def main() -> None:
    entries = {}
    for js in sorted(SCENES.glob("*.js")):
        if js.name == "sources.js":
            continue
        code = js.read_text(encoding="utf-8")
        # second comment line usually names the sketch; fall back to filename
        lines = code.splitlines()
        title = js.stem
        if len(lines) > 1 and lines[1].startswith("//"):
            title = lines[1].lstrip("/ ").strip()
        entries[js.stem] = {"title": title, "code": code}

    out = SCENES / "sources.js"
    body = ",\n".join(
        f"  {json.dumps(k)}: {{ title: {json.dumps(v['title'])}, code: {json.dumps(v['code'])} }}"
        for k, v in entries.items()
    )
    out.write_text(
        "// GENERATED by tools/build_player_sources.py — do not edit by hand.\n"
        "window.SCENES = {\n" + body + "\n};\n",
        encoding="utf-8",
    )
    print(f"[ok] wrote {out} ({len(entries)} scenes)")


if __name__ == "__main__":
    main()
